jobs:
  test:
    docker:
      - image: cirrusci/flutter:stable
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Instalar Just
          command: |
            mkdir -p /tmp/bin
            curl -fsSL https://just.systems/install.sh | bash -s -- --to /tmp/bin
            export PATH="/tmp/bin:$PATH"
      - run:
          name: Ejecutar Tests
          command: just test
