jobs:
  test:
    docker:
      - image: golang
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Ejecutar Test
          command: docker run -u 1001 -t -v `pwd`:/app/test imagen