version: "2"
pipelines:
  test-pipeline:
    tasks:
      - name: Instalar Just
        type: run
        script: mkdir -p /tmp/bin && curl -fsSL https://just.systems/install.sh | bash -s -- --to /tmp/bin
      - name: Instalar Go 1.23
        type: run
        script: 
          - curl -fsSL https://golang.org/dl/go1.23.linux-amd64.tar.gz -o go1.23.tar.gz
          - tar -C /usr/local -xzf go1.23.tar.gz
          - export PATH=$PATH:/usr/local/go/bin
      - name: Ejecutar tests
        type: run
        script: /tmp/bin/just test