trigger:
  - push

jobs:
 job: BuildAndTest
pool:
    vmImage: 'ubuntu-latest'
  teps:
  - task: UseDotNet@2
    inputs:
    packageType: 'sdk'
    version: 'latest'
  
  - task: UseGo@2
    inputs:
    versionSpec: 'latest'
  
  - task: InstallTool@0
    inputs:
    packageType: 'nuget'
    versionSpec: 'latest'
  
  - script: just test
    workingDirectory: $(Build.SourcesDirectory)
#