name: Docker Hub Upload
on:
  push:
    paths:
      - 'go.mod'
      - 'go.sum'
      - 'Dockerfile'
workflow_dispatch:
jobs:
  job1:
    name: Pasar de Docker a Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Construir y lanzar la imagen de Docker
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: antoniorr02/menuconsulter:latest